### ISSUE TITLE
[Feature Request] Add indicator when scrolling is available

### ISSUE THREAD

**Issue by N-Upchurch** [P-Connor/plasma-drawer#23]
Fantastic launcher, first of all; I've been wanting a clean, simple launcher like this that respects directories for a long time. 

It occurs to me that there is no indication to the user signifying that they can scroll through applications or search results. It would be beneficial to have a visible scroll bar, a shadow, or some other affordance to indicate to the user that the list of results / applications extends beyond what is first visible.

**Comment by k4ever** [comment]
This is one of the first things that I noticed that was missing. There is no indicator to let the user know that there are more applications available. Scrolling is also not very easy.

**Comment by P-Connor** [comment]
Funny enough I had a scrollbar implemented for the applications grid, but another feature I added right before release accidentally removed it (lol oops). I will work on getting this back iin the next update. A scrollbar for the search results is a bit more tricky as the size of the list changes depending on what is in view, so this feature may take a bit longer to get out

**Comment by P-Connor** [comment]
```[tasklist]
### Tasks
- [ ] https://github.com/P-Connor/plasma-drawer/issues/27
- [ ] https://github.com/P-Connor/plasma-drawer/issues/28
```

**Comment by P-Connor** [comment]
Apps grid scrollbar complete (#27). Just need search results now (#28)

**Comment by P-Connor** [comment]
Search results scrollbar added by a6eb653597fc40abc0680f1f651702021c39b8f3
