### ISSUE TITLE
[Bug] Scrolling with touch controls is difficult

### ISSUE THREAD

**Issue by P-Connor** [P-Connor/plasma-drawer#36]
Trying to scroll through the applications or search results list tends to select the items rather than scrolling

Steps to reproduce:
1. Open the launcher
2. Navigate to an app directory in which apps run off the screen
3. Attempt to scroll with touch controls

**Comment by k4ever** [comment]
I can definitely confirm this on my Surface Pro touchscreen.

**Comment by P-Connor** [comment]
Fixed by a6eb653597fc40abc0680f1f651702021c39b8f3
