### ISSUE TITLE
[Bug] Widget does not seem to correctly save the path for custom background images.

### ISSUE THREAD

**Issue by HappyHippo77** [P-Connor/plasma-drawer#58]
**Describe the bug**
When the Background configuration is set to "Use image", relogging or restarting the system will cause the widget to forget the path to the image.

**To Reproduce**
1. Create a new Plasma Drawer widget in any panel.
2. Configure it to use a background image.
3. Relog or restart the system.
4. The background image is no longer selected.

**Expected behavior**
The background image should remain selected.

**Device (please complete the following information, which can be found in the KInfoCenter):**
- Distro: Manjaro
- KDE Version: 5.27.10
- KDE Frameworks Version: 5.112.0
- Qt Version: 5.15.11
- Kernel Version: 6.6.7-4-MANJARO
- Graphics Platform: X11
- Device Type (if relevant): Desktop

**Additional context**
The bug is occurring on a highly customized system with a relatively recent Kernel version, therefore the error may be specific to my configuration. It was originally experienced on a Latte panel but the error was repeatedly replicated on KDE panels. I managed to check the Latte configuration file, and it seems that the widget is not saving the path to the configuration anywhere. Attempts to manually write the configuration in were not successful, as I am not particularly experienced with KDE widgets.

**Comment by P-Connor** [comment]
Thanks for the details, I was able to reproduce this issue. Working on a fix now

**Comment by karolpiczak** [comment]
A quick note before I forget about this issue - for Qt 6 the FileDialog API has changed. The `fileUrl` property would need to be changed to `selectedFile`.
